# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
[global]
project_id = "syyaqprmiekyqfoilbna"

[api]
# Port to use for the API URL.
port = 54321

[db]
# Port to use for the DB URL.
port = 54322

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326