name: Deploy Backend to Render

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Only trigger on changes to backend code

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" 