name: Deploy Edge Functions

on:
  push:
    branches:
      - main  # or your default branch
    paths:
      - 'supabase/functions/**'  # Only trigger on changes to edge functions

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: syyaqprmiekyqfoilbna  # Your Supabase project ID

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Edge Functions
        run: |
          supabase link --project-ref $PROJECT_ID
          supabase functions deploy --project-ref $PROJECT_ID 